import hre, { network } from "hardhat";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { keccak256, maxUint256, parseUnits, toBytes, zeroAddress } from "viem";

/**
 * Deploys the protocol + mocks to the running `npx hardhat node`, seeds demo escrows and
 * writes frontend/src/generated/{deployment.json,abis.ts}.
 *
 * Role map over the Hardhat default accounts:
 *   0 guardian, 1 payer, 2 payee, 3/4/5 approvers, 6 oracle operator, 7 arbiter, 8 feed operator
 */
const { viem } = await network.connect();
const publicClient = await viem.getPublicClient();
const wallets = await viem.getWalletClients();
const [guardian, payer, payee, a1, a2, a3, oracleOp, arbiter, feedOp] = wallets;

const usd = await viem.deployContract("MockUSD", []);
const oracle = await viem.deployContract("MockSettlementOracle", [oracleOp.account.address]);
const feed = await viem.deployContract("MockPriceFeed", [feedOp.account.address]);
const escrow = await viem.deployContract("SettlementEscrow", [guardian.account.address, 200n, 3600n]);
const harness = await viem.deployContract("CrossingLawHarness", []);

console.log("MockUSD              ", usd.address);
console.log("MockSettlementOracle ", oracle.address);
console.log("MockPriceFeed        ", feed.address);
console.log("SettlementEscrow     ", escrow.address);
console.log("CrossingLawHarness   ", harness.address);

// fund the payer and pre-approve the escrow
await publicClient.waitForTransactionReceipt({
  hash: await usd.write.mint([payer.account.address, parseUnits("1000000", 6)]),
});
await publicClient.waitForTransactionReceipt({
  hash: await usd.write.approve([escrow.address, maxUint256], { account: payer.account }),
});

// seed two demo escrows
const now = (await publicClient.getBlock()).timestamp;
const approvers = [a1.account.address, a2.account.address, a3.account.address];

const seed1 = await escrow.write.open(
  [
    {
      payee: payee.account.address,
      token: usd.address,
      amount: parseUnits("25000", 6),
      deadline: Number(now) + 7 * 24 * 3600,
      holdWindow: 600,
      quorum: 2,
      approvers,
      oracle: zeroAddress,
      priceFeed: zeroAddress,
      arbiter: arbiter.account.address,
      termsHash: keccak256(toBytes("INV-2026-0917-001: 25,000 USD for 400 units, FOB Rotterdam")),
    },
  ],
  { account: payer.account },
);
await publicClient.waitForTransactionReceipt({ hash: seed1 });

const seed2 = await escrow.write.open(
  [
    {
      payee: payee.account.address,
      token: usd.address,
      amount: parseUnits("120000", 6),
      deadline: Number(now) + 14 * 24 * 3600,
      holdWindow: 900,
      quorum: 2,
      approvers,
      oracle: oracle.address,
      priceFeed: feed.address,
      arbiter: arbiter.account.address,
      termsHash: keccak256(toBytes("INV-2026-0917-002: 120,000 USD, bill of lading + customs proof")),
    },
  ],
  { account: payer.account },
);
await publicClient.waitForTransactionReceipt({ hash: seed2 });

const outDir = path.resolve(process.cwd(), "../frontend/src/generated");
mkdirSync(outDir, { recursive: true });

const deployment = {
  chainId: 31337,
  rpcUrl: "http://127.0.0.1:8545",
  deployedAt: new Date().toISOString(),
  contracts: {
    escrow: escrow.address,
    usd: usd.address,
    oracle: oracle.address,
    feed: feed.address,
    harness: harness.address,
  },
  roles: {
    guardian: guardian.account.address,
    payer: payer.account.address,
    payee: payee.account.address,
    approvers,
    oracleOperator: oracleOp.account.address,
    arbiter: arbiter.account.address,
    feedOperator: feedOp.account.address,
  },
  seededEscrowIds: [1, 2],
};
writeFileSync(path.join(outDir, "deployment.json"), JSON.stringify(deployment, null, 2));
console.log(`deployment written to ${path.join(outDir, "deployment.json")}`);

// ABIs
const names = [
  ["SettlementEscrow", "settlementEscrowAbi"],
  ["CrossingLawHarness", "crossingLawHarnessAbi"],
  ["MockUSD", "mockUsdAbi"],
  ["MockSettlementOracle", "mockSettlementOracleAbi"],
  ["MockPriceFeed", "mockPriceFeedAbi"],
] as const;
let out = "// GENERATED by contracts/scripts/deploy-local.ts — do not edit.\n";
for (const [artifact, exportName] of names) {
  const a = await hre.artifacts.readArtifact(artifact);
  out += `\nexport const ${exportName} = ${JSON.stringify(a.abi, null, 2)} as const;\n`;
}
writeFileSync(path.join(outDir, "abis.ts"), out);
console.log(`ABIs written to ${path.join(outDir, "abis.ts")}`);
