import hre from "hardhat";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

/** Writes the compiled ABIs to frontend/src/generated/abis.ts (typed `as const` for viem). */
export async function exportAbis(outDir: string): Promise<void> {
  const names = [
    ["SettlementEscrow", "settlementEscrowAbi"],
    ["CrossingLawHarness", "crossingLawHarnessAbi"],
    ["MockUSD", "mockUsdAbi"],
    ["MockSettlementOracle", "mockSettlementOracleAbi"],
    ["MockPriceFeed", "mockPriceFeedAbi"],
  ] as const;
  let out = "// GENERATED by contracts/scripts/export-abis.ts — do not edit.\n";
  for (const [artifact, exportName] of names) {
    const a = await hre.artifacts.readArtifact(artifact);
    out += `\nexport const ${exportName} = ${JSON.stringify(a.abi, null, 2)} as const;\n`;
  }
  mkdirSync(outDir, { recursive: true });
  writeFileSync(path.join(outDir, "abis.ts"), out);
  console.log(`ABIs written to ${path.join(outDir, "abis.ts")}`);
}

const outDir = path.resolve(process.cwd(), "../frontend/src/generated");
await exportAbis(outDir);
